"use strict";
const router = require("express").Router();
const { authenticated } = require("../middleware/auth");
const c = require("../controllers/bankReconciliation");
router.use("/payments", authenticated);
router.get("/payments/bank-accounts", c.accounts);
router.post("/payments/bank-accounts", c.createAccount);
router.get("/payments/receipts", c.receipts);
router.post("/payments/receipts", c.uploadMiddleware, c.uploadReceipt);
router.get("/payments/receipts/:id", c.receipt);
router.get("/payments/receipts/:id/file", c.receiptFile);
router.patch("/payments/receipts/:id/fields", c.updateFields);
router.post("/payments/receipts/:id/retry", c.retryReceipt);
router.get("/payments/receipts/:id/candidates", c.candidates);
router.post("/payments/receipts/:id/confirm", c.confirm);
router.get("/payments/statements", c.statements);
router.post("/payments/statements", c.uploadMiddleware, c.uploadStatement);
router.get("/payments/statements/:id", c.statement);
router.get("/payments/statements/:id/file", c.statementFile);
router.post("/payments/statements/:id/retry", c.retryStatement);
router.post("/payments/statements/:id/commit", c.commitStatement);
router.get("/payments/bank-movements", c.movements);
router.get("/payments/owner-credits", c.credits);
module.exports = router;
