"use strict";
const router = require("express").Router();
const { authenticated } = require("../middleware/auth");
const c = require("../controllers/finance");
router.use("/finance", authenticated);
router.get("/finance/options", c.options);
router.get("/finance/condominiums/:id/settings", c.settings);
router.put("/finance/condominiums/:id/settings", c.saveSettings);
router.post("/finance/charges", c.charges);
router.post("/finance/invoices/:id/adjustments", c.adjustment);
router.post("/finance/invoices/:id/credits", c.applyCredit);
router.post("/finance/applications/:id/reversal", c.reverseApplication);
router.get("/finance/credits", c.credits);
router.get("/finance/receivables", c.receivables);
router.get("/finance/history", c.history);
router.post("/finance/late-fees/run", c.runLateFees);
router.get("/finance/entries", c.entries);
router.post("/finance/entries", c.createEntry);
router.post("/finance/entries/:id/reversal", c.reverseEntry);
router.post("/finance/entries/:id/link", c.linkEntry);
router.get("/finance/movements", c.movements);
router.get("/finance/accounts", c.accounts);
router.put("/finance/accounts/:id/opening-balance", c.openingBalance);
router.get("/finance/budget", c.budget);
router.put("/finance/budget", c.saveBudget);
router.get("/finance/report", c.report);
module.exports = router;
