"use strict";
const router = require("express").Router();
const { authenticated } = require("../middleware/auth");
const { requirePlatform } = require("../service/platformAuthorization");
const c = require("../controllers/platform");
const access = require("../controllers/access");
router.use("/platform", authenticated);
const security = require("../controllers/platformSecurity");
const recentMfa = require("../service/platformMfa").requireRecentMfa;
const securityLimit = require("../middleware/registrationRateLimit").createRegistrationRateLimit({ limit: 20 });
router.use("/platform/security", securityLimit);
router.get("/platform/security", security.status);
router.post("/platform/security/setup", security.setup);
router.post("/platform/security/enroll", security.enroll);
router.post("/platform/security/challenge", security.challenge);
router.post("/platform/security/revoke", recentMfa, (req, _res, next) => { req.params.id = req.user.sub; next(); }, security.revoke);
router.post("/platform/security/users/:id/revoke", requirePlatform("platform.supervisors.manage"), recentMfa, security.revoke);
const route = (method, path, permission, ...handlers) => router[method](`/platform${path}`, requirePlatform(permission), ...(method === "get" ? [] : [recentMfa]), ...handlers);
route("get", "/kpis", "platform.kpis.read", c.kpis);
route("get", "/accounts", "platform.accounts.read", c.accounts);
route("get", "/scope-accounts", "platform.supervisors.manage", c.accounts);
route("get", "/supervisor-policies", "platform.supervisors.manage", c.listPolicies);
route("get", "/membership-plans", "platform.memberships.manage", c.listPlans);
route("patch", "/accounts/:subjectType/:subjectId", "platform.accounts.update", c.updateAccount);
route("put", "/memberships/:subjectType/:subjectId", "platform.memberships.manage", c.saveMembership);
route("get", "/policies", "platform.policies.read", c.listPolicies);
route("post", "/policies", "platform.policies.manage", c.savePolicy);
route("put", "/policies/:id", "platform.policies.manage", c.savePolicy);
route("get", "/supervisors", "platform.supervisors.read", c.listUsers);
route("post", "/supervisors", "platform.supervisors.manage", c.saveUser);
route("put", "/supervisors/:id", "platform.supervisors.manage", c.saveUser);
route("get", "/plans", "platform.memberships.read", c.listPlans);
route("post", "/plans", "platform.memberships.manage", c.savePlan);
route("put", "/plans/:id", "platform.memberships.manage", c.savePlan);
route("get", "/audit", "platform.audit.read", c.audits);
route("get", "/audit/:id", "platform.audit.read", c.auditDetail);
const saas = require("../controllers/saas");
route("post", "/plans/:id/publish", "platform.billing.manage", saas.publish);
route("get", "/billing", "platform.billing.read", saas.listBilling);
route("post", "/subscriptions/:id/cancel", "platform.billing.manage", saas.cancelPlatform);
route("post", "/subscriptions/:id/reconcile", "platform.billing.manage", saas.reconcilePlatform);
const migration = require("../controllers/saasMigration");
route("post", "/migrations/preview", "platform.memberships.manage", migration.preview);
route("post", "/migrations/apply", "platform.memberships.manage", migration.apply);
route("get", "/receipts/:id", "platform.billing.read", saas.receipt);
const ops = require("../controllers/platformOperations");
const operationsEnabled = (_req, res, next) => process.env.PLATFORM_OPERATIONS_ENABLED === "true" ? next() : res.status(503).send({ message: "La operación global todavía no está habilitada" });
route("get", "/health", "platform.operations.read", ops.health);
route("post", "/billing/retry", "platform.operations.manage", operationsEnabled, ops.retryBilling);
route("get", "/configuration", "platform.operations.read", ops.configuration);
route("put", "/configuration", "platform.operations.manage", operationsEnabled, ops.saveConfiguration);
route("get", "/support", "platform.support.read", ops.tickets);
route("get", "/support/accounts", "platform.support.read", c.accounts);
route("get", "/communications/accounts", "platform.communications.manage", c.accounts);
route("get", "/lifecycle/accounts", "platform.data.read", c.accounts);
route("post", "/support", "platform.support.manage", operationsEnabled, ops.saveTicket);
route("put", "/support/:id", "platform.support.manage", operationsEnabled, ops.saveTicket);
route("get", "/diagnostics/:subjectType/:subjectId", "platform.support.read", ops.diagnostic);
route("get", "/communications", "platform.communications.read", ops.notices);
route("post", "/communications/preview", "platform.communications.manage", operationsEnabled, ops.previewNotice);
route("post", "/communications/publish", "platform.communications.manage", operationsEnabled, ops.publishNotice);
route("get", "/lifecycle", "platform.data.read", ops.lifecycle);
route("post", "/lifecycle", "platform.data.manage", operationsEnabled, ops.requestClosure);
route("post", "/lifecycle/:id/execute", "platform.data.manage", operationsEnabled, ops.executeClosure);
const lifecycle = require("../controllers/platformLifecycle");
route("post", "/lifecycle/:id/reactivate", "platform.data.manage", operationsEnabled, lifecycle.reactivate);
route("post", "/lifecycle/:id/deletion", "platform.data.manage", operationsEnabled, lifecycle.requestDeletion);
route("post", "/lifecycle/:id/deletion-preview", "platform.data.manage", operationsEnabled, lifecycle.previewDeletion);
route("post", "/lifecycle/:id/delete", "platform.data.manage", operationsEnabled, lifecycle.executeDeletion);
const exportsController = require("../controllers/platformExport");
route("get", "/exports", "platform.data.read", exportsController.list);
route("post", "/exports", "platform.data.read", operationsEnabled, exportsController.create);
route("get", "/exports/:id/download", "platform.data.read", recentMfa, exportsController.download);
for (const [method, path, handler] of [
  ["get", "/catalog", access.catalog], ["get", "/policies", access.listPolicies],
  ["post", "/policies", access.createPolicy], ["put", "/policies/:id", access.updatePolicy],
  ["delete", "/policies/:id", access.archivePolicy], ["get", "/users", access.listAdministrativeUsers],
  ["put", "/grants/:subjectModel/:subjectId", access.upsertGrant],
  ["get", "/condominiums", async (req, res) => res.send({ status: "success", message: await require("../models/condominio").find({ organizationId: req.auth.organizationId }).select("_id alias").lean() })],
]) route(method, `/organizations/:organizationId/access${path}`, method === "get" ? "platform.access.read" : "platform.access.manage", c.organizationContext, handler);
module.exports = router;
