"use strict";
const path = require("node:path"); const fs = require("node:fs/promises"); const assert = require("node:assert/strict"); const express = require("express"); const http = require("node:http");
const { chromium } = require(path.resolve(__dirname, "../../../../tmp/schedule-tools/node_modules/playwright"));
const { fixture } = require("./fixtures"); const { createToken } = require("../../../service/jwt"); const { publicAccessContext } = require("../../../service/authorization");
const { Schedule, ScheduleTask, Record } = require("../infrastructure/models"); const { InternalSchedulerExecutor } = require("../application/executor"); const notices = require("../application/notifications");
const { initializeNotificationRealtime } = require("../../../service/notificationRealtime"); const { Server } = require("socket.io");
async function run() {
  const f = await fixture(process.env.SCHEDULE_TEST_MONGODB_URI);
  const output = path.resolve(__dirname, "../../../../tmp/schedule-browser"); await fs.mkdir(output, { recursive: true });
  const app = express(); app.use(express.json()); app.use("/api", require("../api")); app.use("/api", require("../../../routes/notification"));
  const authMiddleware = require("../../../middleware/auth").authenticated;
  app.get("/api/auth/me", authMiddleware, (req, res) => res.json({ success: true, data: { user: req.auth.account, access: publicAccessContext(req.auth) } }));
  const build = path.resolve(__dirname, "../../../../tmp/schedule-build"); app.use(express.static(build)); app.get(/^\/(?!api\/).*/, (req, res) => res.sendFile(path.join(build, "index.html")));
  const server = http.createServer(app); const io = new Server(server); initializeNotificationRealtime(io);
  await new Promise(resolve => server.listen(0, "127.0.0.1", resolve)); const base = `http://127.0.0.1:${server.address().port}`;
  let browser;
  try {
    browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_EXECUTABLE_PATH });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const identity = { ...f.admin.account, name: "Schedule", lastname: "Admin", avatar: "default-avatar.png", first_password_changed: true };
    await context.addCookies([{ name: "identity", value: JSON.stringify(identity), url: base }, { name: "token", value: createToken(f.admin.account), url: base }, { name: "access_context", value: JSON.stringify(publicAccessContext(f.admin)), url: base }]);
    const page = await context.newPage(); const errors = []; page.on("pageerror", e => errors.push(e.message));
    page.setDefaultTimeout(10000);
    await page.goto(`${base}/#/schedule`);
    await page.getByRole("heading", { name: "Mantenimientos", exact: true }).waitFor().catch(async error => { await page.screenshot({ path: path.join(output, "startup-failure.png"), fullPage: true }); console.error(JSON.stringify({ url: page.url(), errors, body: (await page.locator("body").innerText()).slice(0,1000) })); throw error; });
    await page.screenshot({ path: path.join(output, "initial.png"), fullPage: true });
    await page.getByRole("button", { name: "Programar mantenimiento", exact: true }).click().catch(async error => { console.error(JSON.stringify({ errors, body: (await page.locator("body").innerText()).slice(0,1800) })); throw error; });
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("Nombre", { exact: true }).fill("Limpieza de cisterna E2E");
    await dialog.getByLabel("Ubicación").selectOption("0");
    const due = new Date(Date.now() + 86400000); due.setUTCSeconds(0, 0);
    const local = new Date(due.getTime() - due.getTimezoneOffset() * 60000).toISOString().slice(0,16);
    await dialog.getByLabel("Primer vencimiento", { exact: false }).fill(local);
    await dialog.getByRole("button", { name: "Guardar programación" }).click();
    await dialog.waitFor({ state: "hidden" });
    await page.getByText("Limpieza de cisterna E2E", { exact: true }).waitFor();
    const schedule = await Schedule.findOne({ name: "Limpieza de cisterna E2E" }); assert(schedule);
    await page.getByRole("button", { name: "Pausar", exact: true }).click();
    await page.getByRole("button", { name: "Reanudar", exact: true }).waitFor();
    assert.equal(await new InternalSchedulerExecutor().execute(schedule._id), false);
    await page.getByRole("button", { name: "Reanudar", exact: true }).click(); await page.getByRole("button", { name: "Pausar", exact: true }).waitFor();
    await new InternalSchedulerExecutor().execute(schedule._id); await notices.processOne();
    assert.equal((await notices.inbox(f.admin, 8)).notifications.length, 1);
    const task = await ScheduleTask.findOne({ scheduleId: schedule._id }); assert(task);
    await page.getByRole("button", { name: "Tareas", exact: true }).click();
    await page.getByRole("button", { name: "Reprogramar", exact: true }).click();
    await dialog.getByLabel("Nuevo vencimiento").fill(new Date(due.getTime() + 86400000 - due.getTimezoneOffset() * 60000).toISOString().slice(0,16));
    await dialog.getByRole("button", { name: "Reprogramar", exact: true }).click(); await dialog.waitFor({ state: "hidden" });
    await page.getByRole("button", { name: "Calendario", exact: true }).click(); await page.locator(".fc-event").first().waitFor();
    await page.screenshot({ path: path.join(output, "calendar.png"), fullPage: true });
    await page.getByRole("button", { name: "Lista", exact: true }).click();
    await page.getByRole("button", { name: "Completar", exact: true }).click();
    await dialog.getByLabel("Costo", { exact: true }).fill("1250.50");
    await dialog.getByLabel("Trabajo realizado").fill("Cisterna limpia y verificada.");
    await dialog.getByLabel("Evidencia", { exact: false }).setInputFiles({ name: "receipt.pdf", mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.7\n%%EOF\n") });
    await dialog.getByRole("button", { name: "Completar y guardar historial" }).click(); await dialog.waitFor({ state: "hidden" });
    await page.getByRole("button", { name: "Historial", exact: true }).click(); await page.getByRole("button", { name: "Ver registro", exact: true }).click();
    await dialog.getByText("Cisterna limpia y verificada.", { exact: true }).waitFor();
    const downloadPromise = page.waitForEvent("download"); await dialog.getByRole("button", { name: "receipt.pdf" }).click(); const download = await downloadPromise; assert.equal(download.suggestedFilename(), "receipt.pdf");
    const record = await Record.findOne({ taskId: task._id }); assert.equal(record.evidence.length, 1);
    const next = await Schedule.findById(schedule._id); assert(next.nextRunAt > new Date()); assert.equal(await ScheduleTask.countDocuments({ scheduleId: schedule._id }), 1);
    await page.screenshot({ path: path.join(output, "history.png"), fullPage: true });
    await page.keyboard.press("Escape"); await dialog.waitFor({ state: "hidden" });
    await page.getByRole("button", { name: "Activar modo oscuro", exact: true }).click();
    await page.getByRole("button", { name: "Activar modo claro", exact: true }).waitFor();
    await page.screenshot({ path: path.join(output, "dark.png"), fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.waitForFunction(() => document.querySelector('.layout-main-container').getBoundingClientRect().left < 50);
    await page.waitForFunction(() => document.querySelector('.layout-sidebar').getBoundingClientRect().right < 1);
    await page.screenshot({ path: path.join(output, "mobile.png"), fullPage: true });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'Mobile layout overflows the viewport');
    assert.equal(errors.length, 0, errors.join("\n"));
    // Uploaded test evidence must be removed before the isolated database is dropped.
    await require("../../maintenance/evidence").remove(record.evidence);
    console.log("Schedule browser E2E passed: create, pause/resume, reminder, reschedule, calendar, complete, evidence download, history and mobile");
  } finally {
    if (browser) await browser.close(); await new Promise(resolve => io.close(resolve)); server.closeAllConnections(); if (server.listening) await new Promise(resolve => server.close(resolve)); await f.cleanup();
  }
}
run().catch(error => { console.error(error.stack); process.exitCode = 1; });
