import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { AccountPage, PlatformAccount, PlatformService } from '../../service/platform.service';
import { AccessContextService } from '../../service/access-context.service';
import { global } from '../../service/global.service';
import { stateLabels } from './platform-labels';
interface Row { _id: string; subjectType?: string; subjectId?: string; title?: string; description?: string; state?: string; kind?: string; amountMinor?: number; occurredAt?: string; organizationId?: string; eligibleAfter?: string; assigneeId?: string | null; }
interface Data { rows?: Row[]; charges?: Row[]; subscriptions?: Row[]; total?: number; [key: string]: unknown; }
interface ExportRow { _id: string; organizationId: string; state: string; recordCount: number; expiresAt: string; }
interface DeletionPreview { requestId: string; organizationId: string; slug: string; rows: { collection: string; count: number; preserve: boolean }[]; blockers: string[]; expiresAt: string; token: string; }
interface NoticePreview { title: string; body: string; cutoff: string; expiresAt: string; token: string; recipientCount: number; audience: { mode: string; accounts?: { subjectType: string; subjectId: string }[] }; }
@Component({ standalone: true, selector: 'app-platform-operations', imports: [CommonModule, FormsModule], styleUrl: './platform.css', template: `
<section class="platform-shell"><h1>{{ titles[section] }}</h1><button type="button" (click)="load()" [disabled]="busy()">Actualizar</button>@if (error()) { <p role="alert">{{ error() }}</p> }@if (notice()) { <p role="status">{{ notice() }}</p> }
@if (section === 'billing') { <p>Movimientos de suscripciones a Comunard en USD. Los pagos de condominios se consultan en sus módulos operativos.</p><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Cuenta</th><th>Movimiento</th><th>Importe</th><th>Comprobante</th></tr></thead><tbody>@for (row of rows(); track row._id) { <tr><td>{{ row.occurredAt | date:'dd/MM/yyyy' }}</td><td>{{ row.subjectId }}</td><td>{{ row.kind }}</td><td>{{ (row.amountMinor || 0) / 100 | currency:'USD' }}</td><td><button (click)="receipt(row._id)">Descargar</button></td></tr> }</tbody></table></div><div class="pagination"><button (click)="page = page - 1; load()" [disabled]="page === 1">Anterior</button><span>Página {{ page }}</span><button (click)="page = page + 1; load()" [disabled]="page * 50 >= (data()?.total || 0)">Siguiente</button></div> }
@if (section === 'billing') { <div class="editor"><h2>Suscripciones abiertas</h2><p>Se muestran hasta 100 suscripciones dentro de tu alcance.</p>@for (subscription of data()?.subscriptions || []; track subscription._id) { <p>{{ subscription.subjectId }} · {{ stateLabels[subscription.state || ''] || subscription.state }} @if (access.hasPermission('platform.billing.manage')) { <button (click)="cancellationId = subscription._id; cancellationReason = ''">Cancelar renovación</button><button (click)="reconciliationId = subscription._id; reconciliationReason = ''; providerId = ''">Conciliar con PayPal</button> }</p> }@if (reconciliationId) { <form (ngSubmit)="reconcileSubscription()"><label>ID PayPal (solo si falta el vínculo)<input name="providerId" [(ngModel)]="providerId"></label><label>Motivo de conciliación<textarea name="reconciliationReason" [(ngModel)]="reconciliationReason" required maxlength="500"></textarea></label><button [disabled]="busy() || !reconciliationReason.trim()">Confirmar conciliación</button><button type="button" (click)="reconciliationId = ''">Volver</button></form> }@if (cancellationId) { <form (ngSubmit)="cancelSubscription()"><p>Se conservará el período pagado.</p><label>Motivo de cancelación<textarea name="cancellationReason" [(ngModel)]="cancellationReason" required maxlength="500"></textarea></label><button [disabled]="busy() || !cancellationReason.trim()">Confirmar cancelación de renovación</button><button type="button" (click)="cancellationId = ''">Volver</button></form> }</div> }@if (section === 'support' || (section === 'communications' && access.hasPermission('platform.communications.manage')) || section === 'lifecycle') { <form class="toolbar" (ngSubmit)="findAccounts()"><input name="accountSearch" [(ngModel)]="accountSearch" placeholder="Buscar cuenta"><button>Buscar cuentas</button></form><label>Cuenta<select aria-label="Cuenta" [(ngModel)]="accountId"><option value="">Seleccionar cuenta</option>@for (account of accounts(); track account.id) { <option [value]="account.id">{{ account.name }} — {{ account.subjectType }}</option> }</select></label> }
@if (section === 'support') { <button (click)="diagnostic()" [disabled]="!accountId">Consultar diagnóstico</button>@if (diagnosis()) { <pre>{{ diagnosis() | json }}</pre> }@if (access.hasPermission('platform.support.manage')) { <form class="editor" (ngSubmit)="saveTicket()"><h2>{{ editingId ? 'Editar incidencia' : 'Nueva incidencia' }}</h2><label>Título<input name="title" [(ngModel)]="title" maxlength="150" required></label><label>Descripción<textarea name="description" [(ngModel)]="description" maxlength="2000" required></textarea></label><label>Responsable (ID de supervisor)<input name="assigneeId" [(ngModel)]="assigneeId"></label><label>Estado<select name="state" [(ngModel)]="ticketState"><option value="OPEN">Abierta</option><option value="IN_PROGRESS">En curso</option><option value="RESOLVED">Resuelta</option></select></label><button [disabled]="busy() || !accountId || !title || !description">Guardar incidencia</button></form> } }
@if (section === 'communications' && access.hasPermission('platform.communications.manage')) { <form class="editor" (ngSubmit)="previewNotice()"><label>Título<input name="title" [(ngModel)]="title" required maxlength="150"></label><label>Aviso<textarea name="body" [(ngModel)]="description" required maxlength="2000"></textarea></label><label>Vigencia hasta<input type="date" name="expiresAt" [(ngModel)]="expiresAt" required></label>@if (access.access()?.scope?.mode === 'ALL') { <label><input type="checkbox" name="allAccounts" [(ngModel)]="allAccounts">Todas las cuentas</label> }<button [disabled]="busy() || !title || !description || (!allAccounts && !accountId)">Previsualizar destinatarios</button></form>@if (noticePreview(); as preview) { <div class="editor"><h2>{{ preview.title }}</h2><p>{{ preview.body }}</p><p>{{ preview.recipientCount }} cuentas destinatarias</p><button (click)="publishNotice()" [disabled]="busy()">Publicar este aviso</button></div> } }
@if (section === 'configuration') { <form class="editor" (ngSubmit)="saveConfig()"><label>Retención tras baja (días)<input type="number" name="retentionDays" [(ngModel)]="retentionDays" min="7" max="3650"></label><label>Correo de soporte<input type="email" name="supportEmail" [(ngModel)]="supportEmail"></label><label>Mensaje de mantenimiento<textarea name="maintenanceMessage" [(ngModel)]="maintenanceMessage" maxlength="2000"></textarea></label>@if (access.hasPermission('platform.operations.manage')) { <button [disabled]="busy()">Guardar configuración</button> }</form> }
@if (section === 'health') { <pre>{{ data() | json }}</pre>@if (access.hasPermission('platform.operations.manage')) { <button (click)="retryBilling()" [disabled]="busy()">Reintentar conciliación SaaS</button> } }
@if (section === 'lifecycle' && access.hasPermission('platform.data.manage')) { <form class="editor" (ngSubmit)="requestClosure()"><p>La baja conserva los datos y requiere revisión de otro operador.</p><label>Motivo<textarea name="reason" [(ngModel)]="description" maxlength="500" required></textarea></label><button [disabled]="busy() || !accountId || !description">Solicitar baja de organización</button></form> }
@if (section === 'lifecycle') { <div class="editor"><h2>Exportaciones de organización</h2><p>Incluyen registros y referencias a adjuntos. Los archivos originales y las credenciales no se incluyen.</p><button [disabled]="busy() || !accountId" (click)="requestExport()">Generar exportación</button>@for (job of exports(); track job._id) { <p>{{ job.organizationId }} · {{ stateLabels[job.state] || job.state }} · {{ job.recordCount }} registros @if (job.state === 'READY') { <button (click)="downloadExport(job._id)">Descargar NDJSON</button> }</p> }</div> }
@if (section !== 'billing' && section !== 'configuration' && section !== 'health') { <div class="table-wrap"><table><thead><tr><th>Referencia</th><th>Estado</th><th>Acción</th></tr></thead><tbody>@for (row of rows(); track row._id) { <tr><td>{{ row.title || row.organizationId }}<small>{{ row.description || row._id }}</small></td><td>{{ stateLabels[row.state || ''] || row.state }}</td><td>@if (section === 'support' && access.hasPermission('platform.support.manage')) { <button (click)="editTicket(row)">Editar</button> }@if (section === 'lifecycle' && row.state === 'REQUESTED' && access.hasPermission('platform.data.manage')) { <button (click)="closureId = row._id">Revisar baja</button> }@if (section === 'lifecycle' && access.hasPermission('platform.data.manage')) { @if (row.state === 'CLOSED' || row.state === 'DELETION_REQUESTED') { <button (click)="chooseLifecycle(row, 'reactivate')">Reactivar</button> }@if (row.state === 'CLOSED') { <button (click)="chooseLifecycle(row, 'deletion')">Solicitar borrado</button> }@if (row.state === 'DELETION_REQUESTED') { <button (click)="chooseLifecycle(row, 'delete')">Revisar borrado físico</button> } }</td></tr> }</tbody></table></div> }
@if (closureId) { <div class="editor"><p>Confirmar bloqueará el acceso de esta organización y comenzará su período de retención.</p><button (click)="executeClosure()" [disabled]="busy()">Confirmar baja</button><button (click)="closureId = ''">Volver</button></div> }@if (lifecycleId) { <form class="editor" (ngSubmit)="confirmLifecycle()"><h2>{{ lifecycleAction === 'delete' ? 'Revisión de borrado físico' : lifecycleAction === 'deletion' ? 'Solicitar borrado tras retención' : 'Reactivar organización' }}</h2>@if (lifecycleAction === 'delete') { @if (deletionPreview(); as preview) { <pre>{{ preview.rows | json }}</pre><p>Los registros marcados preserve permanecen por su retención financiera o de auditoría.</p>@for (blocker of preview.blockers; track blocker) { <p role="alert">{{ blocker }}</p> }<label>Escribe {{ preview.slug }} para confirmar<input name="deletionConfirmation" [(ngModel)]="deletionConfirmation" required></label><button [disabled]="busy() || preview.blockers.length > 0 || deletionConfirmation !== preview.slug">Confirmar borrado irreversible</button> } }@else { <label>Motivo<textarea name="lifecycleReason" [(ngModel)]="lifecycleReason" required maxlength="500"></textarea></label><button [disabled]="busy() || !lifecycleReason.trim()">Confirmar operación</button> }<button type="button" (click)="lifecycleId = ''">Volver</button></form> }</section>` })
export class PlatformOperationsComponent {
  private readonly api = inject(PlatformService); private readonly http = inject(HttpClient); readonly access = inject(AccessContextService);
  readonly section = String(inject(ActivatedRoute).snapshot.data['section']);
  readonly titles: Record<string, string> = { billing: 'Facturación del SaaS', support: 'Soporte de plataforma', communications: 'Avisos de plataforma', configuration: 'Configuración global', health: 'Operación técnica', lifecycle: 'Ciclo de vida de organizaciones' };
  readonly data = signal<Data | null>(null); readonly rows = signal<Row[]>([]); readonly accounts = signal<PlatformAccount[]>([]); readonly diagnosis = signal<unknown>(null); readonly noticePreview = signal<NoticePreview | null>(null); readonly busy = signal(false); readonly error = signal(''); readonly notice = signal('');
  readonly stateLabels = stateLabels;
  readonly exports = signal<ExportRow[]>([]);
  readonly deletionPreview = signal<DeletionPreview | null>(null);
  cancellationId = ''; cancellationReason = '';
  reconciliationId = ''; reconciliationReason = ''; providerId = '';
  reconcileSubscription(): void { this.busy.set(true); this.api.post(`subscriptions/${this.reconciliationId}/reconcile`, { reason: this.reconciliationReason, providerId: this.providerId }).subscribe({ next: () => { this.reconciliationId = ''; this.saved(); }, error: e => this.failed(e) }); }
  cancelSubscription(): void { this.busy.set(true); this.api.post(`subscriptions/${this.cancellationId}/cancel`, { reason: this.cancellationReason }).subscribe({ next: () => { this.cancellationId = ''; this.saved(); }, error: e => this.failed(e) }); }
  lifecycleId = ''; lifecycleAction = ''; lifecycleReason = ''; deletionConfirmation = '';
  chooseLifecycle(row: Row, action: string): void { this.lifecycleId = row._id; this.lifecycleAction = action; this.lifecycleReason = ''; this.deletionConfirmation = ''; this.deletionPreview.set(null); if (action === 'delete') this.api.post<DeletionPreview>(`lifecycle/${row._id}/deletion-preview`).subscribe({ next: data => this.deletionPreview.set(data), error: e => this.failed(e) }); }
  confirmLifecycle(): void { this.busy.set(true); this.api.post(`lifecycle/${this.lifecycleId}/${this.lifecycleAction}`, this.lifecycleAction === 'delete' ? { preview: this.deletionPreview(), confirmation: this.deletionConfirmation } : { reason: this.lifecycleReason }).subscribe({ next: () => { this.lifecycleId = ''; this.saved(); }, error: e => this.failed(e) }); }
  page = 1; accountSearch = ''; accountId = ''; title = ''; description = ''; assigneeId = ''; ticketState = 'OPEN'; editingId = ''; expiresAt = ''; allAccounts = false; retentionDays = 90; supportEmail = ''; maintenanceMessage = ''; closureId = '';
  constructor() { this.load(); if (['support', 'lifecycle'].includes(this.section) || (this.section === 'communications' && this.access.hasPermission('platform.communications.manage'))) this.findAccounts(); }
  load(): void { this.api.get<Data>(`${this.section}?page=${this.page}`).subscribe({ next: data => { this.data.set(data); this.rows.set(data.rows || data.charges || []); if (this.section === 'configuration') { this.retentionDays = Number(data['retentionDays']); this.supportEmail = String(data['supportEmail']); this.maintenanceMessage = String(data['maintenanceMessage']); } }, error: e => this.failed(e) }); if (this.section === 'lifecycle') this.api.get<ExportRow[]>('exports').subscribe({ next: jobs => this.exports.set(jobs), error: e => this.failed(e) }); }
  findAccounts(): void { this.api.get<AccountPage>(`${this.section}/accounts?search=${encodeURIComponent(this.accountSearch)}${this.section === 'lifecycle' ? '&subjectType=ORGANIZATION' : ''}`).subscribe({ next: data => this.accounts.set(this.section === 'lifecycle' ? data.rows.filter(row => row.subjectType === 'ORGANIZATION') : data.rows), error: e => this.failed(e) }); }
  private account(): PlatformAccount | undefined { return this.accounts().find(row => row.id === this.accountId); }
  diagnostic(): void { const account = this.account(); if (account) this.api.get<unknown>(`diagnostics/${account.subjectType}/${account.id}`).subscribe({ next: data => this.diagnosis.set(data), error: e => this.failed(e) }); }
  editTicket(row: Row): void { this.editingId = row._id; this.accountId = row.subjectId || ''; this.title = row.title || ''; this.description = row.description || ''; this.assigneeId = row.assigneeId || ''; this.ticketState = row.state || 'OPEN'; }
  saveTicket(): void { const account = this.account(); if (!account) return; this.busy.set(true); this.api.save('support', { subjectType: account.subjectType, subjectId: account.id, title: this.title, description: this.description, state: this.ticketState, assigneeId: this.assigneeId }, this.editingId || undefined).subscribe({ next: () => { this.editingId = ''; this.saved(); }, error: e => this.failed(e) }); }
  previewNotice(): void { const account = this.account(); this.busy.set(true); this.api.post<NoticePreview>('communications/preview', { title: this.title, body: this.description, mode: this.allAccounts ? 'ALL' : 'SELECTED', accounts: account ? [{ subjectType: account.subjectType, subjectId: account.id }] : [], expiresAt: this.expiresAt ? this.expiresAt + 'T23:59:59-04:00' : '' }).subscribe({ next: data => { this.noticePreview.set(data); this.busy.set(false); }, error: e => this.failed(e) }); }
  publishNotice(): void { this.busy.set(true); this.api.post('communications/publish', { preview: this.noticePreview() }).subscribe({ next: () => { this.noticePreview.set(null); this.saved(); }, error: e => this.failed(e) }); }
  saveConfig(): void { this.busy.set(true); this.http.put(`${global.url}platform/configuration`, { retentionDays: this.retentionDays, supportEmail: this.supportEmail, maintenanceMessage: this.maintenanceMessage }).subscribe({ next: () => this.saved(), error: e => this.failed(e) }); }
  retryBilling(): void { this.busy.set(true); this.api.post('billing/retry').subscribe({ next: () => this.saved(), error: e => this.failed(e) }); }
  requestClosure(): void { this.busy.set(true); this.api.post('lifecycle', { organizationId: this.accountId, reason: this.description }).subscribe({ next: () => this.saved(), error: e => this.failed(e) }); }
  requestExport(): void { this.busy.set(true); this.api.post('exports', { organizationId: this.accountId }).subscribe({ next: () => this.saved(), error: e => this.failed(e) }); }
  downloadExport(id: string): void { this.http.get(`${global.url}platform/exports/${id}/download`, { responseType: 'blob' }).subscribe({ next: blob => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `comunard-${id}.ndjson`; a.click(); URL.revokeObjectURL(url); }, error: e => this.failed(e) }); }
  executeClosure(): void { this.busy.set(true); this.api.post(`lifecycle/${this.closureId}/execute`).subscribe({ next: () => { this.closureId = ''; this.saved(); }, error: e => this.failed(e) }); }
  receipt(id: string): void { this.http.get(`${global.url}platform/receipts/${id}`, { responseType: 'blob' }).subscribe({ next: blob => { const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `comunard-${id}.json`; a.click(); URL.revokeObjectURL(url); }, error: e => this.failed(e) }); }
  private saved(): void { this.busy.set(false); this.error.set(''); this.notice.set('Operación registrada.'); this.load(); }
  private failed(e: unknown): void { this.busy.set(false); this.error.set(this.api.errorMessage(e)); }
}




